-- Development-only discovery inbox samples. Run with `supabase db reset` for a local Supabase instance.
insert into public.discovered_opportunities (title, organization_name, description, category, representation_type, event_date, application_deadline, location, event_url, source_name, source_url, relevance_score, visibility_score, networking_score, stakeholder_value_score, feasibility_score, recommendation_summary, discovery_status, discovered_at)
select * from (values
  ('Sri Lanka Youth Leadership Summit 2026', 'National Youth Services Council', 'A national youth leadership forum seeking panel participants.', 'youth_forum', 'panel', '2026-11-12'::date, '2026-10-01'::date, 'Colombo', 'https://example.com/youth-summit', 'Partner newsletter', 'https://example.com/source/youth-summit', 88, 82, 78, 75, 80, 'Strong youth audience and credible visibility for AIESEC representation.', 'new', now() - interval '1 day'),
  ('Sustainable Business Forum Sri Lanka', 'Ceylon Chamber of Commerce', 'Corporate sustainability forum with a partnership and exhibition track.', 'corporate_event', 'partnership', '2026-10-20'::date, '2026-09-20'::date, 'Colombo', 'https://example.com/sustainable-business', 'Event calendar', 'https://example.com/source/sustainable-business', 76, 84, 81, 90, 68, 'High stakeholder value with a practical route to corporate partnerships.', 'reviewing', now() - interval '3 days'),
  ('University Innovation Challenge', 'University of Moratuwa', 'Student innovation competition with a media and networking opportunity.', 'university_event', 'networking', '2026-09-28'::date, '2026-09-12'::date, 'Moratuwa', 'https://example.com/innovation-challenge', 'University announcement', 'https://example.com/source/innovation', 72, 65, 86, 70, 85, 'Useful campus network opportunity with an imminent application deadline.', 'new', now() - interval '5 days'),
  ('South Asia SDG Dialogue', 'UNDP Sri Lanka', 'Regional dialogue on youth participation in the Sustainable Development Goals.', 'sdg_event', 'speaking', '2026-12-04'::date, '2026-10-25'::date, 'Colombo', 'https://example.com/sdg-dialogue', 'NGO partner referral', 'https://example.com/source/sdg-dialogue', 95, 90, 85, 92, 72, 'Exceptional mission alignment and high-level stakeholder access.', 'new', now() - interval '6 hours')
) as seed(title, organization_name, description, category, representation_type, event_date, application_deadline, location, event_url, source_name, source_url, relevance_score, visibility_score, networking_score, stakeholder_value_score, feasibility_score, recommendation_summary, discovery_status, discovered_at)
where not exists (select 1 from public.discovered_opportunities where title = seed.title);
